name: Tibia Data Scraper

on:
  schedule:
    - cron: '*/3 * * * *'  # Every 3 minutes
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]  # Run on push for testing

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
    
    - name: Run scraper
      run: python Test-scarper-4-bot.py
      
    - name: Check for changes
      id: verify-changed-files
      run: echo "changed=$(git diff --quiet . || echo 'true')" >> $GITHUB_OUTPUT
    
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"
        git add -A
        git commit -m "Update Tibia data - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        git push
